development:
  adapter: postgresql
  encoding: unicode
  database: estydemo_development
  pool: 5
  username: taiwo
  host: localhost

test:
  adapter: postgresql
  database: estydemo_test
  pool: 5
  username: taiwo
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: estydemo_production
  pool: 5
  username: aries
  password: